language: android
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-25.0.0
    - android-23
    - extra-android-m2repository

before_install:
  - chmod +x gradlew
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
  - export ENV_CI=true

script: ./gradlew clean build --info --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)